package paquetitos.servidor.entidades;

import java.util.List;
import javax.json.bind.annotation.JsonbTransient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 * Destinatarios generated by hbm2java
 */
@XmlRootElement(name = "envio")
@Entity
@Table(name = "destinatarios", catalog = "paquetitos")
public class Destinatarios implements java.io.Serializable {

    private Integer idDestinatario;
    private Clientes clientes;
    private String nombreDestinatario;
    private String dninif;
    private String codigoPostal;
    private String direccionCompleta;

    public Destinatarios() {
    }

    public Destinatarios(Clientes clientes, String nombreDestinatario, String codigoPostal, String direccionCompleta) {
        this.clientes = clientes;
        this.nombreDestinatario = nombreDestinatario;
        this.codigoPostal = codigoPostal;
        this.direccionCompleta = direccionCompleta;
    }

    public Destinatarios(Clientes clientes, String nombreDestinatario, String dninif, String codigoPostal,
            String direccionCompleta) {
        this.clientes = clientes;
        this.nombreDestinatario = nombreDestinatario;
        this.dninif = dninif;
        this.codigoPostal = codigoPostal;
        this.direccionCompleta = direccionCompleta;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "IdDestinatario", unique = true, nullable = false)
    public Integer getIdDestinatario() {
        return this.idDestinatario;
    }

    public void setIdDestinatario(Integer idDestinatario) {
        this.idDestinatario = idDestinatario;
    }

    @XmlTransient
    @JsonbTransient
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Idcliente", nullable = false)
    public Clientes getClientes() {
        return this.clientes;
    }

    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

    @Column(name = "NombreDestinatario", nullable = false, length = 200)
    public String getNombreDestinatario() {
        return this.nombreDestinatario;
    }

    public void setNombreDestinatario(String nombreDestinatario) {
        this.nombreDestinatario = nombreDestinatario;
    }

    @Column(name = "DNINIF", length = 10)
    public String getDninif() {
        return this.dninif;
    }

    public void setDninif(String dninif) {
        this.dninif = dninif;
    }

    @Column(name = "CodigoPostal", nullable = false, length = 10)
    public String getCodigoPostal() {
        return this.codigoPostal;
    }

    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    @Column(name = "DireccionCompleta", nullable = false, length = 250)
    public String getDireccionCompleta() {
        return this.direccionCompleta;
    }

    public void setDireccionCompleta(String direccionCompleta) {
        this.direccionCompleta = direccionCompleta;
    }

}
